name: Update README.md

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
    
      - name: cat readme
        run: cat README.md

      - name: Print Asset URL
        run: |
          git fetch
          git fetch --tags
          export tag_name=$(git tag --list --sort=-version:refname "v*-bootstrap" | head -n 1)
          echo $tag_name
          export version=$(echo "${tag_name#*v}" | awk -F. '{print $1"."$2"."$3+0}')
          echo $version
          git checkout $tag_name
          export github_url="https://api.github.com/repos/unigrid-project/janus-java-testing/releases/tags/"
          export releases=$(curl -s $github_url$tag_name)
          echo $releases
          asset_urls=$(echo $releases | jq -r '.assets[].browser_download_url')
          echo $asset_urls
          for asset in $(echo $json | jq -r '.assets[] | @base64'); do
              _jq() {
                echo ${asset} | base64 --decode | jq -r ${1}
              }
              echo $(_jq '.browser_download_url')
              sed -ri 's/v[0-9\.]+/v'$version'/g' README.md
              sed -ri 's/d-[0-9\.]+/d-'$version'/g' README.md
              sed -ri 's/d_[0-9\.]+/d_'$version'/g' README.md
              sed -ri 's/dmg/.dmg/g' README.md
              sed -ri 's/msi/.msi/g' README.md
          done

      - name: cat readme
        run: cat README.md