name: Update README.md

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Asset URL
        run: |
          export tag=$(git tag --list --sort=-version:refname "v*-bootstrap" | head -n 1)
          export github_url="https://api.github.com/repos/unigrid-project/janus-java-testing/releases/tags/${tag}"
          export releases=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" $github_url)
          asset_urls=$(echo ${releases} | jq -r '.assets[].browser_download_url')

          IFS=$'\n' read -rd '' -a asset_array <<< "${asset_urls}"
          for asset_url in "${asset_array[@]}"; do
            echo "Asset URL: $asset_url"
          done
