name: Create release & tag

on:
  repository_dispatch:
    types:
    - dispatch-release
  workflow_dispatch:
    inputs:
      target_module:
        description: 'Target module'
        type: choice
        options:
        - fx
        - bootstrap
      tag_name:
        description: 'Module tag'
        required: true
      parent_tag:
        description: 'Parent tag'
        required: false

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - run: echo 'target_module=${{ inputs.target_module }}, tag_name=${{ inputs.tag_name }}, parent_tag=${{ inputs.parent_tag }}'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'

      - name: Set up JDK 17
        if: ${{ inputs.parent_tag == '' && github.event.client_payload.parent_tag == '' }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        if: ${{ inputs.parent_tag == '' && github.event.client_payload.parent_tag == '' }}
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Maven version
        if: ${{ inputs.parent_tag == '' && github.event.client_payload.parent_tag == '' }}
        run: mvn -v

      - name: Set parent tag
        run: |
          if [[ -z "${{ inputs.parent_tag }}${{ github.event.client_payload.parent_tag }}" ]]; then
            echo "parent_tag=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          else
            echo "parent_tag=${{ inputs.parent_tag }}${{ github.event.client_payload.parent_tag }}" >> $GITHUB_ENV
          fi

      - name: Set parent tag
        run: |
          echo "env parent_tag = ${{ env.parent_tag }}"

      - uses: rickstaa/action-create-tag@v1
        name: Create tag
        id: "tag_create_tag"
        with:
          tag: ${{ inputs.tag_name }}${{ github.event.client_payload.tag_name }}_${{ inputs.target_module }}${{ github.event.client_payload.target_module }}
          tag_exists_error: false
          message: "Tag created by github action"

      - uses: rickstaa/action-create-tag@v1
        name: Create parent tag
        id: "tag_create_parent_tag"
        with:
          tag: ${{ env.parent_tag }}
          tag_exists_error: false
          message: "Tag created by github action"

      - uses: ncipollo/release-action@v1
        name: Release tag
        with:
          name: ${{ inputs.tag_name }}${{ github.event.client_payload.tag_name }}_${{ inputs.target_module }}${{ github.event.client_payload.target_module }}
          tag: ${{ inputs.tag_name }}${{ github.event.client_payload.tag_name }}_${{ inputs.target_module }}${{ github.event.client_payload.target_module }}
          generateReleaseNotes: true
          draft: true
