name: Dispatcher

on:
  workflow_dispatch:
    inputs:
      target_module:
        description: 'Target module'
        type: choice
        options:
        - bootstrap
        - fx
      bump:
        description: 'Bump version'
        type: choice
        options:
        - Revision
        - Minor
        - Major
      update_repo:
        description: 'Update repo (on main, for the configs)'
        type: choice
        options:
        - unigrid-update-testing
        - unigrid-update
      skip_test:
        type: boolean
        description: Skip test
        default: false

env:
  GH_TOKEN: ${{ secrets.ACTION_PAT }}
  owner: unigrid-project

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      max-parallel: 1
      matrix:
        release: ['test', 'set-version', 'create-release', 'upload', 'bump', 'update-config']
        include:
          - release: test
            name: Test suite
            event: dispatch-test
            inputs: '{"skip_fx": "false","skip_bootstrap": "false","skip_desktop": "false","skip_config": "false","skip_checkstyle": "false"}'
            payload: '{"skip_test": "${{ inputs.skip_test }}"}'
            check: 'Maven test'
            workflow: 'ubuntu-deb-test-suite.yml'
            repo: '${{ github.repository }}'
            branch: '${{ github.ref_name }}'

          - release: set-version
            name: Set version & Remove snapshot
            event: dispatch-set-version
            inputs: '{"target_module": "${{ inputs.target_module }}"}'
            check: 'Set version'
            workflow: 'ubuntu-deb-set-version.yml'
            repo: '${{ github.repository }}'
            branch: '${{ github.ref_name }}'

          - release: create-release
            name: Create release & tag
            event: dispatch-release
            inputs: '{"tag_name": "${{ inputs.tag_name }}-${{ inputs.target_module }}"}'
            check: 'Create release'
            workflow: 'ubuntu-deb-release-create.yml'
            repo: '${{ github.repository }}'
            branch: '${{ github.ref_name }}'

          - release: upload
            name: Upload to release tag
            event: dispatch-upload
            inputs: '{"tag_name": "${{ inputs.tag_name }}","target_module": "${{ inputs.target_module }}","skip_ubuntu": "false","skip_windows": "false","skip_macos": "false"}'
            check: 'Upload to release'
            workflow: 'upload.yml'
            repo: '${{ github.repository }}'
            branch: '${{ github.ref_name }}'

          - release: bump
            name: Bump version
            event: dispatch-bump
            inputs: '{"target_module": "${{ inputs.target_module }}","bump": "${{ inputs.bump }}"}'
            check: 'Bump'
            workflow: 'ubuntu-deb-bump.yml'
            repo: '${{ github.repository }}'
            branch: '${{ github.ref_name }}'

          - release: update-config
            name: Update config files
            event: dispatch-update-config
            check: 'Update config'
            workflow: 'ubuntu-deb-update-config.yml'
            repo: '${{ inputs.update_repo }}'
            branch: 'main'

    steps:
      - name: Test branch
        run: echo test branch here, ${{ matrix.test_branch }}

      - name: Check if skip this dispatch job
        if: >
          matrix.event == 'dispatch-test' && inputs.skip_test == true
        run: echo "skip=true" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        if: env.skip != 'true'

      - name: Dispatch an action and get the run ID
        if: env.skip != 'true'
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.ACTION_PAT }}
          ref: ${{ matrix.branch }}
          repo: ${{ matrix.repo }}
          owner: ${{ env.owner }}
          workflow:  ${{ matrix.workflow }}
          workflow_inputs: ${{ matrix.inputs }}
          workflow_timeout_seconds: 120

      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        if: env.skip != 'true'
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.ACTION_PAT }}
          repo: ${{ matrix.repo }}
          owner: ${{ env.owner }}
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 600
