name: Test suite

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        type: string
        description: 'distinct_id used by return-dispatch'
      skip_fx:
        type: boolean
        description: Skip fx
        default: true
      skip_bootstrap:
        type: boolean
        description: Skip bootstrap
        default: true
      skip_desktop:
        type: boolean
        description: Skip desktop
        default: true
      skip_config:
        type: boolean
        description: Skip config
        default: true
      skip_checkstyle:
        type: boolean
        description: Skip checkstyle
        default: true
  # Triggers the workflow At minute 0 past every 6th hour
  schedule:
    - cron: "0 */6 * * *"

jobs:
  test:
    name: Maven test
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: echo distinct ID ${{ inputs.distinct_id }}
        if: inputs.distinct_id != ''
        run: echo ${{ inputs.distinct_id }}

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Requires builds
        run: |
          xvfb-run -a mvn -f config/pom.xml install -Dcheckstyle.skip -Dmaven.test.skip=true
          xvfb-run -a mvn -f pom.xml install -Dcheckstyle.skip -Dmaven.test.skip=true
          xvfb-run -a mvn -f bootstrap/pom.xml install -Dcheckstyle.skip -Dmaven.test.skip=true

      - name: Test fx
        run: |
          if [[ ${{ inputs.skip_fx }} == 'false' ]]; then
            xvfb-run -a mvn -f fx/pom.xml test -Dcheckstyle.skip
          fi

      - name: Test bootstrap
        run: |
          if [[ ${{ inputs.skip_bootstrap }} == 'false' ]; then
            xvfb-run -a mvn -f bootstrap/pom.xml test -Dcheckstyle.skip
          fi

      - name: Test desktop
        run: |
          if [[ ${{ inputs.skip_desktop }} == 'false'  then
            xvfb-run -a mvn -f desktop/pom.xml test -Dcheckstyle.skip
          fi

      - name: Test config
        run: |
          if [[ ${{ inputs.skip_config }} == 'false' then
            xvfb-run -a mvn -f config/pom.xml test -Dcheckstyle.skip
          fi

      - name: Test checkstyle
        run: |
          if [[ ${{ inputs.skip_checkstyle }} == 'false' ]]; then
            xvfb-run -a mvn checkstyle:check
          fi
