name: Add snapshot

on:
  workflow_dispatch:
    inputs:
      skip_parent:
        type: boolean
        description: Skip parent
        default: false
      skip_fx:
        type: boolean
        description: Skip fx
        default: false
      skip_bootstrap:
        type: boolean
        description: Skip bootstrap
        default: false
      skip_desktop:
        type: boolean
        description: Skip desktop
        default: false
      generate_backup_poms:
        type: boolean
        description: Generate backup poms
        default: false
      update_matching_versions:
        type: boolean
        description: Update matching versions
        default: false

env:
  skip_parent: ${{ inputs.skip_parent }}
  skip_fx: ${{ inputs.skip_fx }}
  skip_bootstrap: ${{ inputs.skip_bootstrap }}
  skip_desktop: ${{ inputs.skip_desktop }}

jobs:
  add-snapshot:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Java version
        run: java --version

      - name: Maven version
        run: mvn -v

      - name: Requires config build
        run: mvn -f config/pom.xml clean install -Dcheckstyle.skip -Dmaven.test.skip=true

      - name: set env variables
        run: |
          for module in parent fx bootstrap desktop; do
            if [[ $module == 'parent' ]]; then
              echo "$(echo version_$(echo $module))=$(mvn -f pom.xml -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV
            elif [[ $module == 'desktop' ]]; then
              echo "$(echo version_$(echo $module))=$(echo $bootstrap_version)" >> $GITHUB_ENV
            else
              echo "$(echo version_$(echo $module))=$(mvn -f $(echo $module)/pom.xml -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV
            fi
          done

      - name: Snapshot action
        run: |
          for module in parent fx bootstrap desktop; do
            if [[ $(printenv skip_$module) == false ]]; then
              if [[ $(printenv version_$module) != *-SNAPSHOT*  ]]; then
                if [[ $module == 'parent' ]]; then
                  mvn -f pom.xml versions:set -DnewVersion=$(printenv version_$module)-SNAPSHOT -DgenerateBackupPoms=${{ inputs.generate_backup_poms }} -DupdateMatchingVersions=${{ inputs.update_matching_versions }}
                elif [[ $module == 'desktop' ]]; then
                  mvn -f $module/pom.xml versions:set -DnewVersion=$(printenv version_bootstrap)-SNAPSHOT -DgenerateBackupPoms=${{ inputs.generate_backup_poms }} -DupdateMatchingVersions=${{ inputs.update_matching_versions }}
                else
                  mvn -f $module/pom.xml versions:set -DnewVersion=$(printenv version_$module)-SNAPSHOT -DgenerateBackupPoms=${{ inputs.generate_backup_poms }} -DupdateMatchingVersions=${{ inputs.update_matching_versions }}
                fi
              fi
            fi
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Github actions add snapshot 
