name: Bump version

on:
  repository_dispatch:
    types:
    - dispatch-bump
  workflow_dispatch:
    inputs:
      skip_fx:
        type: boolean
        description: Skip fx
        default: false
      skip_bootstrap:
        type: boolean
        description: Skip bootstrap
        default: false
      skip_desktop:
        type: boolean
        description: Skip desktop
        default: false
      generate_backup_poms:
        type: boolean
        description: Generate backup poms
        default: false
      update_matching_versions:
        type: boolean
        description: Update matching versions
        default: false

env:
  skip_fx: ${{ inputs.skip_fx }}
  skip_bootstrap: ${{ inputs.skip_bootstrap }}
  skip_desktop: ${{ inputs.skip_desktop }}

jobs:
  bump-version:
    name: Bump
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Version checks
        run: |
          java --version
          mvn -v

      - name: Requires config build
        run: mvn -f config/pom.xml clean install -Dcheckstyle.skip -Dmaven.test.skip=true

      - name: Bump version
        run: |
          for module in fx desktop bootstrap; do
            export version_$module=$(mvn -f $(echo $module)/pom.xml -q -DforceStdout help:evaluate -Dexpression=project.version)
            mvn -f $module/pom.xml versions:set -DnewVersion=$(printenv version_$module)-SNAPSHOT -DgenerateBackupPoms=${{ inputs.generate_backup_poms }} -DupdateMatchingVersions=${{ inputs.update_matching_versions }}
            if [[ $(printenv skip_$module) == false ]]; then
              mvn -f $module/pom.xml versions:set -DnextSnapshot=true -DgenerateBackupPoms=${{ inputs.generate_backup_poms }} -DupdateMatchingVersions=${{ inputs.update_matching_versions }}
            fi
          done
          export version_parent=$(mvn -f pom.xml -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          mvn -f pom.xml versions:set -DnewVersion=$(printenv version_parent)-SNAPSHOT -DgenerateBackupPoms=${{ inputs.generate_backup_poms }} -DupdateMatchingVersions=${{ inputs.update_matching_versions }}
          mvn -f pom.xml versions:set -DnextSnapshot=true -DgenerateBackupPoms=${{ inputs.generate_backup_poms }} -DupdateMatchingVersions=${{ inputs.update_matching_versions }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Github actions bump version
