name: Test suite

on:
  repository_dispatch:
    types:
    - dispatch-test
  workflow_dispatch:
    inputs:
      distinct_id:
        type: string
        description: 'distinct_id'
      skip_fx:
        type: boolean
        description: Skip fx
        default: false
      skip_bootstrap:
        type: boolean
        description: Skip bootstrap
        default: false
      skip_desktop:
        type: boolean
        description: Skip desktop
        default: false
      skip_config:
        type: boolean
        description: Skip config
        default: false
      skip_checkstyle:
        type: boolean
        description: Skip checkstyle
        default: false
  # Triggers the workflow At minute 0 past every 6th hour
  schedule:
    - cron: "0 */6 * * *"

jobs:
  test:
    name: Maven test
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: echo distinct ID ${{ inputs.distinct_id }}
        run: echo ${{ inputs.distinct_id }}
      - run: 'echo "input.skip_fx: ${{ inputs.skip_fx }}"'
      - run: 'echo "skip_test field: ${{ github.event.client_payload.skip_test }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Version checks
        run: |
          java --version
          mvn -v

      - name: Requires builds
        run: |
          if [[ ${{ github.event.client_payload.skip_test }} == 'false' || -z "${{ inputs.skip_fx }}${{ github.event.client_payload.skip_test }}" ]]; then
            xvfb-run -a mvn -f config/pom.xml install -Dcheckstyle.skip -Dmaven.test.skip=true
            xvfb-run -a mvn -f pom.xml install -Dcheckstyle.skip -Dmaven.test.skip=true
            xvfb-run -a mvn -f bootstrap/pom.xml install -Dcheckstyle.skip -Dmaven.test.skip=true
          fi

      - name: Test fx
        run: |
          if [[ ${{ inputs.skip_fx }}${{ github.event.client_payload.skip_test }} == 'false' || -z "${{ inputs.skip_fx }}${{ github.event.client_payload.skip_test }}" ]]; then
            xvfb-run -a mvn -f fx/pom.xml test -Dcheckstyle.skip
          fi

      - name: Test bootstrap
        run: |
          if [[ ${{ inputs.skip_bootstrap }}${{ github.event.client_payload.skip_test }} == 'false' || -z "${{ inputs.skip_bootstrap }}${{ github.event.client_payload.skip_test }}" ]]; then
            xvfb-run -a mvn -f bootstrap/pom.xml test -Dcheckstyle.skip
          fi

      - name: Test desktop
        run: |
          if [[ ${{ inputs.skip_desktop }}${{ github.event.client_payload.skip_test }} == 'false' || -z "${{ inputs.skip_desktop }}${{ github.event.client_payload.skip_test }}" ]]; then
            xvfb-run -a mvn -f desktop/pom.xml test -Dcheckstyle.skip
          fi

      - name: Test config
        run: |
          if [[ ${{ inputs.skip_config }}${{ github.event.client_payload.skip_test }} == 'false' || -z "${{ inputs.skip_config }}${{ github.event.client_payload.skip_test }}" ]]; then
            xvfb-run -a mvn -f config/pom.xml test -Dcheckstyle.skip
          fi

      - name: Test checkstyle
        run: |
          if [[ ${{ inputs.skip_checkstyle }}${{ github.event.client_payload.skip_test }} == 'false' || -z "${{ inputs.skip_checkstyle }}${{ github.event.client_payload.skip_test }}" ]]; then
            xvfb-run -a mvn checkstyle:check
          fi
