name: Create release & tag

on:
  repository_dispatch:
    types:
    - dispatch-release
  workflow_dispatch:
    inputs:
      distinct_id:
        type: string
        description: 'distinct_id used by return-dispatch'
      tag_name:
        description: 'Module tag'
        required: true
      parent_tag:
        description: 'Parent tag'
        required: false

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: echo distinct ID ${{ inputs.distinct_id }}
        if: inputs.distinct_id != ''
        run: echo ${{ inputs.distinct_id }}

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        if: ${{ inputs.parent_tag == '' }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        if: ${{ inputs.parent_tag == '' }}
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Set parent tag
        run: |
          if [[ -z "${{ inputs.parent_tag }}" ]]; then
            echo "parent_tag=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          else
            echo "parent_tag=${{ inputs.parent_tag }}" >> $GITHUB_ENV
          fi

      - uses: rickstaa/action-create-tag@v1
        name: Create tag
        id: "tag_create_tag"
        with:
          tag: ${{ inputs.tag_name }}
          tag_exists_error: false
          message: "Tag created by github action"

      - uses: rickstaa/action-create-tag@v1
        name: Create parent tag
        id: "tag_create_parent_tag"
        with:
          tag: ${{ env.parent_tag }}
          tag_exists_error: false
          message: "Tag created by github action"

      - uses: ncipollo/release-action@v1
        name: Release tag
        with:
          name: ${{ inputs.tag_name }}
          tag: ${{ inputs.tag_name }}
          generateReleaseNotes: true
          draft: true
