name: Dispatcher

on:
  workflow_dispatch:
    inputs:
      target_module:
        description: 'Target module'
        type: choice
        options:
        - bootstrap
        - fx
      bump:
        description: 'Bump version'
        type: choice
        options:
        - Revision
        - Minor
        - Major
      update_repo:
        description: 'Update repo (on main, for the configs)'
        type: choice
        options:
        - unigrid-update-testing
        - unigrid-update
      skip_test:
        type: boolean
        description: Skip test
        default: false

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      max-parallel: 1
      matrix:
        release: ['maven-release-tag', 'create-release', 'upload', 'update-config']
        include:
          - release: test
            name: Maven release tag
            inputs: '{"target_module": "${{ inputs.target_module }}","bump": "${{ inputs.bump }}","skip_test": "${{ inputs.skip_test }}"}'
            check: 'Release tag'
            workflow: 'ubuntu-deb-maven-release.yml'
            repo: '${{ github.event.repository.name }}'
            branch: '${{ github.ref_name }}'

          - release: create-release
            name: Create release & tag
            inputs: '{"target_module": "${{ inputs.target_module }}","bump": "${{ inputs.bump }}"}'
            check: 'Create release'
            workflow: 'ubuntu-deb-release-create.yml'
            repo: '${{ github.event.repository.name }}'
            branch: '${{ github.ref_name }}'

          - release: upload
            name: Upload to release tag
            inputs: '{"target_module": "${{ inputs.target_module }}","bump": "${{ inputs.bump }}","skip_ubuntu": "false","skip_windows": "false","skip_macos": "false"}'
            check: 'Upload to release'
            workflow: 'upload.yml'
            repo: '${{ github.event.repository.name }}'
            branch: '${{ github.ref_name }}'

          - release: update-config
            name: Update config files
            check: 'Update config'
            workflow: 'ubuntu-deb-update-config.yml'
            repo: '${{ inputs.update_repo }}'
            branch: 'main'

    steps:
      - uses: actions/checkout@v3

      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.ACTION_PAT }}
          ref: ${{ matrix.branch }}
          repo: ${{ matrix.repo }}
          owner: ${{ github.repository_owner }}
          workflow:  ${{ matrix.workflow }}
          workflow_inputs: ${{ matrix.inputs }}
          workflow_timeout_seconds: 120

      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.ACTION_PAT }}
          repo: ${{ matrix.repo }}
          owner: ${{ github.repository_owner }}
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 600
