name: Update README.md

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Print Asset URL
        run: |
          export tag_name=$(git tag --list --sort=-version:refname "v*-bootstrap" | head -n 1)
          echo $tag_name
          git checkout $tag_name
          export github_url="https://api.github.com/repos/unigrid-project/janus-java-testing/releases/tags/"
          export releases=$(curl -s $github_url$tag_name)
          echo $releases
          asset_urls=$(echo $releases | jq -r '.assets[].browser_download_url')
          echo asset_urls
          for asset in $(echo $json | jq -r '.assets[] | @base64'); do
              _jq() {
                echo ${asset} | base64 --decode | jq -r ${1}
              }
              echo $(_jq '.browser_download_url')
          done
