name: Create release & tag

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        type: string
        description: 'distinct_id used by return-dispatch'
      target_module:
        description: 'Target module'
        type: choice
        options:
        - bootstrap
        - fx

env:
  tag_delimeter: '-'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: echo distinct ID ${{ inputs.distinct_id }}
        if: inputs.distinct_id != ''
        run: echo ${{ inputs.distinct_id }}

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Requires config build
        run: xvfb-run -a mvn -f config/pom.xml install -Dcheckstyle.skip -Dmaven.test.skip=true

      - name: Set parent tag
        run: |
          echo "tag_parent=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "tag_name=v$(mvn -f $(echo ${{ inputs.target_module }})/pom.xml -q -DforceStdout help:evaluate -Dexpression=project.version)${{ env.tag_delimeter }}${{ inputs.target_module }}" >> $GITHUB_ENV

      - uses: rickstaa/action-create-tag@v1
        name: Create tag
        with:
          tag: ${{ env.tag_name }}
          tag_exists_error: false
          message: "Tag created by github action"

      - uses: rickstaa/action-create-tag@v1
        name: Create parent tag
        with:
          tag: ${{ env.tag_parent }}
          tag_exists_error: false
          message: "Tag created by github action"

      - uses: ncipollo/release-action@v1
        name: Release tag
        with:
          name: ${{ env.tag_name }}
          tag: ${{ env.tag_name }}
          generateReleaseNotes: true
          draft: true
