name: Update README.md

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Print Asset URL
        run: |
          git fetch
          git fetch --tags
          export tag_name=$(git tag --list --sort=-version:refname "v*-bootstrap" | head -n 1)
          echo $tag_name
          git checkout $tag_name
          export github_url="https://api.github.com/repos/unigrid-project/janus-java-testing/releases/tags/"
          export releases=$(curl -s $github_url$tag_name)
          echo $releases
          asset_urls=$(echo $releases | jq -r '.assets[].browser_download_url')
          echo $asset_urls
          IFS=$'\n' read -rd '' -a asset_array <<< "$asset_urls"
          for asset_url in "${asset_array[@]}"; do
            echo "Asset URL: $asset_url"
          done